// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,side:68}
export const parser = LRParser.deserialize({
  version: 13,
  states: "'UOcQPOOPkOPOOOsQPO'#C`O!vQPO'#C_O!}QPO'#CgO#SQPO'#ChOOQO'#Ci'#CiQcQPOOPOOO'#C]'#C]POOO)C>c)C>cOOQO,59P,59POOQO'#Cc'#CcO#XQPO'#CcO#^QPO'#CcOOQO'#Cb'#CbO#fQPO'#CbO#qQPO'#CeOOQO'#Ca'#CaOOQO'#Cj'#CjO$]QPO,58yO$dQPO'#CfOOQO,58y,58yO$rQPO,58yOOQO'#C`'#C`O%YQPO,59RO%aQPO,59SOOQO-E6g-E6gOOQO,58},58}O%fQPO,58}O%kQQO,58|OOQO-E6h-E6hOOQO1G.e1G.eO%|QPO1G.eOOQO,59Q,59QO&RQPO1G.mOOQO1G.m1G.mOOQO1G.n1G.nOOQO1G.i1G.iOOQO'#Cd'#CdO$dQPO'#CkO&YQQO1G.hOOQO1G.h1G.hOOQO7+$P7+$POOQO7+$X7+$XOOQO,59V,59VOOQO-E6i-E6iOOQO7+$S7+$S",
  stateData: "&m~ObOScOSdOSePQfPQ~OgQOtSO~OeWOfWO~OqYOgSXhSXiSXjSXkSXrSXsSXuXX~Og`Oh]Oi[OjZOk_OrdO~OseO~P!bOggO~OuiO~OjkO~OilOjkO~Oh]Oi[OjZO~OqYOgXXhXXiXXjXXkXXrXXsXX~OsoO~P!bOh]Oi[OjZOk_O~OsoO~Og`Oh]Oi[OjZOk_O~OssO~P$wOstO~OjuO~OlvOmvOnvOovOpyO~OszO~Os{O~P$wOlvOmvOnvOovOp!OO~Oi~",
  goto: "#Y`PaPdhou!R!^!b!ldd!r!x#SRXPTUOVSROVRhSXbRchrWaRchrQqdR|w[^RcdhrwRm_TwmxSTOVXaRchrQfRRpcQVORjVQcRSncrRrhQxmR}x",
  nodeNames: "⚠ Comment Program Instruction Opcode Parameter NumberParam Value Operator WordParam Sideset Directive Label",
  maxTerm: 37,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "&v~RfXY!gYZ!u[]!gpq!gqr!ztu#`z{#q{|#v|}#{}!O$Q!O!P$a!P!Q$f!Q!R%c!R![%t![!]&S!]!^&a!_!`!z!c!}!z!}#O&l#P#Q&q#R#S!z#T#o!z~!lRc~XY!g[]!gpq!g~!zOs~~#PTg~qr!z!_!`!z!c!}!z#R#S!z#T#o!z~#cPYZ#f~#iP#Q#R#l~#qOd~~#vOn~~#{Om~~$QOb~R$XPlQiP}!O$[P$aOqP~$fOt~~$kPo~z{$n~$qROz$nz{$z{~$n~$}TOz$nz{$z{!P$n!P!Q%^!Q~$n~%cOe~~%hSj~!Q![%t#U#V%|#c#d%|#l#m%|~%yPj~!Q![%t~&PP!Q![%t~&XPu~![!]&[~&aOh~~&fQf~OY&aZ~&a~&qOk~~&vOp~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 23, get: value => spec_identifier[value] || -1}],
  tokenPrec: 257
})
