// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Instruction = 3,
  Opcode = 4,
  Parameter = 5,
  NumberParam = 6,
  Value = 7,
  Operator = 8,
  WordParam = 9,
  Sideset = 10,
  Directive = 11,
  Label = 12
